### ISSUE TITLE
Some preliminary analysis

### ISSUE THREAD

**Issue by vbordign** [ZiluTian/ml_project1#10]
1. Missing data
Remove missing data for this analysis:
2. Statistical characteristics of features (mean, std), types of variables
3. Check each feature 1 degree regression
4. Correlation with output
5. Cross correlation with each other

**Comment by ZiluTian** [comment]
1. separate categorical data (PRI_jet_num)
2. get cross-coefficent and cross-covariance matrix (subsample=False) (visualize with a graph) 
3. use PCA analysis to get the eigen values of the cross-coef/cov 
4. Decide on features (top eigen values)  (~10)

**Comment by ZiluTian** [comment]
Ridge regression on features to evaluate the model (cross validation of 4 datasets on subsamples of actual data with predicted missing values)
